Controllers/CarrinhoController.cs
using InduMovel.Models;
using InduMovel.Repositories.Interfaces;
using InduMovel.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace InduMovel.Controllers
{
    [Authorize]
    public class CarrinhoController : Controller
    {
        private readonly Carrinho _carrinho;
        private readonly IMovelRepository _movelRepository;
        public CarrinhoController(Carrinho carrinho, IMovelRepository movelRepository)
        {
            _carrinho = carrinho;
            _movelRepository = movelRepository;
        }
        public IActionResult Index()
        {
            var itens = _carrinho.GetCarrinhoCompraItems();
            _carrinho.CarrinhoItens = itens;
            var carrinhoVM = new CarrinhoViewModel
            {
                Carrinho = _carrinho,
                CarrinhoTotal = _carrinho.GetCarrinhoCompraTotal()
            };
            return View(carrinhoVM);
        }
        public IActionResult AdicionarItemNoCarrinhoCompra(int movelId)
        {
            var movelSelecionado = _movelRepository.Moveis.FirstOrDefault(l => l.MovelId == movelId);
            if (movelSelecionado != null)
            {
                _carrinho.AdicionarItemCarrinho(movelSelecionado);
            }
            return RedirectToAction("Index");
        }
        public IActionResult RemoverCarrinho(int movelId)
        {
            var movelSelecionado = _movelRepository.Moveis.FirstOrDefault(l => l.MovelId == movelId);
            if (movelSelecionado != null)
            {
                _carrinho.RemoverItemDoCarrinhoCompra(movelSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/MovelController.cs
using InduMovel.Models;
using InduMovel.Repositories.Interfaces;
using InduMovel.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace InduMovel.Controllers
{
    public class MovelController : Controller
    {
        private readonly IMovelRepository _movelRespository;
        public MovelController(IMovelRepository movelRespository)
        {
            _movelRespository = movelRespository;
        }
        public IActionResult List(string categoria)
        {
            IEnumerable<Movel> moveis;
            var categoriaAtual = string.Empty;
            if (string.IsNullOrEmpty(categoria))
            {
                moveis = _movelRespository.Moveis.OrderBy(m => m.MovelId);
                categoriaAtual = "Todos os itens";
            }
            else
            {
                moveis = _movelRespository.Moveis.Where(m =>
                m.Categoria.Nome.Equals(categoria)).OrderBy(m => m.MovelId);

                categoriaAtual = categoria;
            }
            var movelListViewMovel = new MovelListViewModel
            {
                Moveis = moveis,
                CategoriaAtual = categoriaAtual
            };
            return View(movelListViewMovel);
        }
        public IActionResult Details(int movelId)
        {

            var movel = _movelRespository.Moveis.FirstOrDefault(m =>

            m.MovelId == movelId);

            return View(movel);
        }
        public IActionResult Search(string searchString)
        {

            IEnumerable<Movel> moveis;
            string categoriaAtual = string.Empty;
            if (string.IsNullOrEmpty(searchString))
            {
                moveis = _movelRespository.Moveis.OrderBy(m => m.Nome);
                categoriaAtual = "Todos os Itens";
            }
            else
            {
                moveis = _movelRespository.Moveis.Where(m =>
                m.Nome.ToLower() == searchString.ToLower()).OrderBy(m => m.Nome);

                if (moveis.Any())
                {
                    categoriaAtual = "Itens";
                }
                else
                {
                    categoriaAtual = "Nada encontrado";
                }
            }
            return View("~/Views/Movel/List.cshtml", new
            MovelListViewModel
            {
                CategoriaAtual = categoriaAtual,
                Moveis = moveis
            });

        }
    }
}

Views/Shared/_Card.cshtml
<div class="col-sm-4 col-md-4 col-lg-4">
    <p><img src="@Model.ImagemUrl" class="img-fluid" asp-append-version="true"></p>
    <h3>Preço : @Model.Valor.ToString("c")</h3>
    <h4>
        <a asp-controller="Movel" asp-action="Details" asp-route-movelId="@Model.MovelId">@Model.Nome</a>
    </h4>
    <p>@Model.Descricao</p>
    <div>
        <p class="button">
            <a class="btn btn-primary" id="cartButton" asp-controller="Carrinho"
                asp-action="AdicionarItemNoCarrinhoCompra" asp-route-movelId="@Model.MovelId">
                Incluir no Carrinho
            </a>
        </p>
    </div>
</div>

Views/Shared/_Carousel.cshtml
<div id="carouselMoveis" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/imagens/Movel1.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/imagens/Movel2.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/imagens/Movel3.jpg" class="d-block w-100" alt="...">
        </div>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselMoveis" data-bs- slide="prev">

        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>

    <button class="carousel-control-next" type="button" data-bs-target="#carouselMoveis" data-bs- slide="next">

        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InduMovel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InduMovel.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InduMovel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">

                            @await Component.InvokeAsync("CategoriaMenu")

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Admin"))
                            {

                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Admin" asp-
                                    action="Index">Admin</a>

                            }
                        </li>
                        <li class="nav-item">

                            <form class="navbar-form navbar-right" asp-controller="Movel" asp-action="Search"
                                method="get">

                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Procurar

produto" name="searchString" value="@ViewData["searchString"]">
                                </div>
                            </form>
                        </li>
                        <li>@await Component.InvokeAsync("CarrinhoResumo")</li>
                        <li>
                            @await Html.PartialAsync("_Login")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - InduMovel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_Login.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<UserAccount> SignInManager
@if(SignInManager.IsSignedIn(User))
{
<form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
method="post" class="navbar-left">
<ul class="nav navbar-nav navbar-left">
<button type="submit" style="width:auto" class="nav-link btn btn-link">
<strong> Logout : @User.Identity.Name &nbsp; </strong>
</button>
</ul>
</form>
}
else
{
<ul class="nav navbar-nav navbar-left">

<a class="nav-link text-dark" asp-controller="Account" asp-action="Login" asp-route-returnUrl="@string.Format("{0}{1}",Context.Request.Path, Context.Request.QueryString)"

style="color:black">&nbsp; Log in&nbsp; </a>
<a class="nav-link text-dark" asp-controller="Account" asp-action="Register"
style="color:black">&nbsp;Registro&nbsp;&nbsp;&nbsp;</a>
</ul>
}